=== khaledboussaba/exemples_xml/schema/ex1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <!-- on commence par les elements simples -->
    <xs:element name="titre" type="xs:string" />
    <xs:element name="auteur" type="xs:string" />
    <xs:element name="tome" type="xs:string" />
    <xs:element name="nbPage" type="xs:string" />
    <xs:element name="editeur" type="xs:string" />
    <xs:element name="lieuEdition" type="xs:string" />
    <xs:element name="lieuImpression" type="xs:string" />
    <xs:element name="ISBN" type="xs:string" />
    <xs:element name="nomJournal" type="xs:string" />
    <xs:element name="anneePublication" type="xs:string" />
    <xs:element name="numeroJournal" type="xs:string" />
    <xs:element name="numeroPage" type="xs:string" />
    <xs:element name="avis" type="xs:string" />
    
    
    <xs:element name="tomes">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="tome" />
                <xs:element ref="nbPage" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="infoPublication">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="nomJournal" />
                <xs:element ref="anneePublication" />
                <xs:element ref="numeroJournal" />
                <xs:element ref="numeroPage" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="infoEdition">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="editeur" />
                <xs:element ref="lieuEdition" />
                <xs:element ref="lieuImpression" />
                <xs:element ref="ISBN" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="livre">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titre" />
                <xs:element ref="auteur" maxOccurs="unbounded" />
                <xs:element ref="tomes" />
                <xs:element ref="infoEdition" />
                <xs:element ref="avis" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="article">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="titre" />
                <xs:element ref="auteur" maxOccurs="unbounded" />
                <xs:element ref="infoPublication" />
                <xs:element ref="avis" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:element name="bibliographie">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element ref="livre" />
                <xs:element ref="article" />
            </xs:choice>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== khaledboussaba/exemples_xml/schema/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliographie xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="ex1.xsd">
    <livre>
        <titre></titre>
        <auteur></auteur>
        <tomes>
            <tome></tome>
            <nbPage></nbPage>
            <tome></tome>
            <nbPage></nbPage>
        </tomes>
        <infoEdition>
            <editeur></editeur>
            <lieuEdition></lieuEdition>
            <lieuImpression></lieuImpression>
            <ISBN></ISBN>
        </infoEdition>
        <avis></avis>
    </livre>
    <article>
        <titre>Programmer en Java</titre>
        <auteur>Auteur1</auteur>
        <infoPublication>
            <nomJournal></nomJournal>
            <anneePublication></anneePublication>
            <numeroJournal></numeroJournal>
            <numeroPage></numeroPage>
        </infoPublication>
        <avis></avis>
    </article>
</bibliographie>
