=== khaledboussaba/exemples_xml/dtd/exo/ex3.dtd
<!ELEMENT composition (auteur, date_de_creation, fleuriste?, composants) >
<!ELEMENT auteur (#PCDATA) >
<!ELEMENT date_de_creation (#PCDATA) >
<!ELEMENT fleuriste (ville | lieu) >
<!ELEMENT ville (#PCDATA) >
<!ELEMENT lieu (#PCDATA) >
<!ELEMENT composants (vase, fleurs) >
<!ELEMENT vase (matiere, taille) >
<!ELEMENT matiere (#PCDATA) >
<!ELEMENT taille (#PCDATA) >
<!ELEMENT fleurs (nature, item+) >
<!ELEMENT nature (#PCDATA) >
<!ELEMENT item (#PCDATA) >

=== khaledboussaba/exemples_xml/dtd/exo/ex3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE composition SYSTEM "ex3.dtd">
<composition>
    <auteur>Floristore</auteur>
    <date_de_creation>29/02/2001</date_de_creation>
    <fleuriste>
        <ville>Paris</ville>
    </fleuriste>
    <composants>
        <vase>
            <matiere>Porcelaine</matiere>
            <taille>50X70 cm</taille>
        </vase>
        <fleurs>
            <nature>Europeenne</nature>
            <item>Tulipe</item>
            <item>Glaieul</item>
            <item>Marguerite</item>
        </fleurs>
    </composants>
</composition>
