=== khaledboussaba/exemples_xml/dtd/exo/ex6.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bibliographie (livres*,articles*) >
<!ELEMENT livres (livre+) >
<!ELEMENT livre (titre, auteurs, tomes, infos, avis_personnel?) >
<!ELEMENT titre (#PCDATA) >
<!ATTLIST titre sous_titre CDATA #IMPLIED >
<!ELEMENT auteurs (auteur+) >
<!ELEMENT auteur (#PCDATA) >
<!ELEMENT tomes (tome+) >
<!ELEMENT tome EMPTY >
<!ATTLIST tome 
    nbre_page CDATA #REQUIRED 
    sous_titre CDATA #IMPLIED
>
<!ELEMENT infos (nom_editeur, lieu_edition, numero_ISBN) >
<!ELEMENT nom_editeur (#PCDATA) >
<!ELEMENT lieu_edition (#PCDATA) >
<!ELEMENT numero_ISBN (#PCDATA) >
<!ELEMENT avis_personnel (#PCDATA) >

<!ELEMENT articles (article+) >
<!ELEMENT article (titre, auteurs, references, avis_personnel?) >
<!ELEMENT references (num_page, num_journal) >
<!ELEMENT num_page (#PCDATA) >
<!ELEMENT num_journal (#PCDATA) >
<!ATTLIST references 
    nom_journal CDATA "Feuille de chou" 
    annee_publication (2000 | 2001 | inconnue) "inconnue"
>

=== khaledboussaba/exemples_xml/dtd/exo/ex6.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bibliographie SYSTEM "ex6.dtd">
<bibliographie>
    <livres>
        <livre>
            <titre></titre>
            <auteurs>
                <auteur></auteur>
            </auteurs>
            <tomes>
                <tome nbre_page="" sous_titre=""></tome>
            </tomes>
            <infos>
                <nom_editeur></nom_editeur>
                <lieu_edition></lieu_edition>
                <numero_ISBN></numero_ISBN>
            </infos>
            <avis_personnel></avis_personnel>
        </livre>
    </livres>
    <articles>
        <article>
            <titre></titre>
            <auteurs>
                <auteur></auteur>
            </auteurs>
            <references nom_journal="">
                <num_page></num_page>
                <num_journal></num_journal>
            </references>
        </article>
    </articles>
</bibliographie>
